### ISSUE TITLE
make same local & docker mysql host name

### ISSUE THREAD

**Issue by baram204** [baram204/Used-Car-Price-Expectation-with-ML#25]
inside flask container... `mysql:// ....@db/` possible.
but, local windwos can't 

```
 flask:
    image: tiangolo/uwsgi-nginx-flask:python3.6
    container_name: flask_server
    volumes:
      - ../flaskapp:/app
    ports:
      - "8886:80"
    environment:
      - FLASK_APP=app/main.py
      - FLASK_DEBUG=1
      - PYTHONPATH=/app/app
    links:
      - db
```
