### ISSUE TITLE
build jupyter-notebook container for adding additional package

### ISSUE THREAD

**Issue by baram204** [baram204/Used-Car-Price-Expectation-with-ML#6]
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-f35047f3c1ff> in <module>()
      8 from bs4 import BeautifulSoup
      9 import re # 정규식 지원
---> 10 import MySQLdb # mysql 지원
     11 from sqlalchemy import create_engine # 데이터베이스 툴킷
     12 

ModuleNotFoundError: No module named 'MySQLdb'
```

**Comment by baram204** [comment]
ref below :

https://github.com/gifford-lab/jupyter-docker-stacks/blob/master/datascience-notebook/Dockerfile

make change  for different image building: 

```
  jupyter:
    container_name:   notebook
#    image: jupyter/datascience-notebook
    build:
      context: ./jupyter
      dockerfile: Dockerfile
```

ah!!!! wait again to download!! not again!! :(

download is to slow....
